import { Inter } from "next/font/google";
import "./globals.css";
import TopNavbar from "./components/TopNavbar";
import SideNavbar from "./components/SideNavbar";

const inter = Inter({
  subsets: ["latin"],
  weight:["200","400","500", "600","700"],
  variable: "--font-inter"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavbar />
        <div className="flex min-h-screen overflow-x-auto">
          <SideNavbar />
          <main className="flex-1 bg-[#F0F9FF]">
            {children}
          </main>

        </div>
      </body>
    </html>
  );
}
